Repository micronaut-projects/micronaut-validation, pull requests merged in 2024-01, with the labels that each got.

#165 bug: props with optional getters should be validated
  validation/src/test/groovy/io/micronaut/validation/validator/ValidatorSpec.groovy
Labels: type: bug

#280 [validation] Update common files for branch master
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#289 extract methods
  validation/src/main/java/io/micronaut/validation/validator/constraints/DefaultInternalConstraintValidatorFactory.java
Labels: type: improvement

#287 Fix resetting `disableDefaultConstraintViolation`
  validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java
  validation/src/main/java/io/micronaut/validation/validator/constraints/ConstraintValidator.java
  validation/src/test/groovy/io/micronaut/validation/validator/constraints/disable/DisableDefaultConstraintViolationSpec.groovy
  validation/src/test/groovy/io/micronaut/validation/validator/constraints/disable/NotNullMessageFromAnnotation.java
  validation/src/test/groovy/io/micronaut/validation/validator/constraints/disable/NotNullMessageFromAnnotationValidator.java
  validation/src/test/groovy/io/micronaut/validation/validator/constraints/disable/NotNullMessageFromValidator.java
  validation/src/test/groovy/io/micronaut/validation/validator/constraints/disable/NotNullMessageFromValidatorValidator.java
  validation/src/test/groovy/io/micronaut/validation/validator/constraints/disable/ValueObject.java
Labels: type: bug

#301 [validation] Update common files for branch master
  .github/workflows/publish-snapshot.yml
Labels: relates-to: build
